version: 2.1

workflows:
  build-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: felicianotech/docker-hugo:0.47.1
    steps:
      - checkout
      - run:
          name: HUGO build for Test domain
          command: |
            hugo -v -s exampleSite --destination /tmp/public -b http://localhost
            ls /tmp/public
            if [ ! -f /tmp/public/index.html ];then
              echo "index.html not created, failing"
              exit 1
            fi
      - run:
          name: Start Local Server
          background: true
          command: |
            hugo server -v -s exampleSite -b http://localhost --themesDir ../..
      - run:
          name: Check Content  
          command: |
            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" http://localhost:1313/index.html`
            if [ "$HTTPCODE" -ne 200 ];then
              echo "index.html not found, failing"
              exit 1
            fi
